apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: ragdb-postgres
    url: postgres:5432
    user: rag
    secureJsonData:
      password: rag
    jsonData:
      database: ragdb
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
